use Mix.Config

# Configure your database
config :united, United.Repo,
  username: "postgres",
  password: "postgres",
  database: "#{System.get_env("SNAME")}_dev",
  hostname: "localhost",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with webpack to recompile .js and .css sources.
config :united, UnitedWeb.Endpoint,
  http: [port: 4009],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :united, UnitedWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/united_web/(live|views)/.*(ex)$",
      ~r"lib/united_web/templates/.*(eex)$"
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :united, :facebook,
  accounting_url: System.get_env("ACCOUNTING_URL"),
  base_url: System.get_env("FB_CALLBACK") |> String.split("/fb_callback") |> List.first(),
  callback_url: System.get_env("FB_CALLBACK")

config :united, United.Mailer, adapter: Bamboo.LocalAdapter

config :united, :firebase,
  apiKey: System.get_env("G_API_KEY"),
  authDomain: System.get_env("FIREBASE_AUTH_DOMAIN"),
  projectId: System.get_env("FIREBASE_PROJECT_ID"),
  storageBucket: System.get_env("FIREBASE_BUCKET"),
  messagingSenderId: System.get_env("FIREBASE_MSID"),
  appId: System.get_env("FIREBASE_APPID")

# config :united, United.Mailer,
#   adapter: Bamboo.SMTPAdapter,
#   server: "smtp.mailersend.net",
#   hostname: "united",
#   port: 587,
#   username: "MS_dRNg0i@trial-3zxk54vnnpxljy6v.mlsender.net",
#   password: "JsbM22Z1GRDYmDcO",
#   tls: :always,
#   allowed_tls_versions: [:"tlsv1.2"],
#   tls_log_level: :error,
#   tls_verify: :verify_none,
#   ssl: false,
#   retries: 1,
#   no_mx_lookups: false,
#   auth: :if_available

# config :united, United.Mailer,
#   adapter: Bamboo.SMTPAdapter,
#   server: "smtp.mailersend.net",
#   hostname: "united_app",
#   port: 587,
#   username: System.get_env("MS_USERNAME"),
#   password: System.get_env("MS_PW"),
#   tls: :always,
#   allowed_tls_versions: [:"tlsv1.2"],
#   tls_log_level: :error,
#   tls_verify: :verify_none,
#   ssl: false,
#   retries: 1,
#   no_mx_lookups: false,
#   auth: :if_available
